/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication11;

/**
 *
 * @author Gabriel Medina
 */
public class Horario extends javax.swing.JFrame {

    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void limpiarTabla() {
        for (int i = 1; i <= 5; i++) {
            jTable1.setValueAt("", 0, i);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        menuItem1 = new java.awt.MenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        lunes = new javax.swing.JCheckBox();
        martes = new javax.swing.JCheckBox();
        miercoles = new javax.swing.JCheckBox();
        jueves = new javax.swing.JCheckBox();
        viernes = new javax.swing.JCheckBox();
        primeraH = new javax.swing.JCheckBox();
        segundaH = new javax.swing.JCheckBox();
        terceraH = new javax.swing.JCheckBox();
        cuartaH = new javax.swing.JCheckBox();
        quintaH = new javax.swing.JCheckBox();
        sextaH = new javax.swing.JCheckBox();
        dia = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        menuItem1.setLabel("menuItem1");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"15:00-15:55", null, null, null, null, null},
                {"15:55-16:50", null, null, null, null, null},
                {"16:50-17:45", null, null, null, null, null},
                {"17:45-18:00", "Descanso", "Descanso", "Descanso", "Descanso", "Descanso"},
                {"18:00-18:55", null, null, null, null, null},
                {"18:55-19:50", null, null, null, null, null},
                {"19:50-20:45", null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        lunes.setText("Lunes");
        lunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesActionPerformed(evt);
            }
        });

        martes.setText("Martes");
        martes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martesActionPerformed(evt);
            }
        });

        miercoles.setText("Miercoles");
        miercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miercolesActionPerformed(evt);
            }
        });

        jueves.setText("Jueves");
        jueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juevesActionPerformed(evt);
            }
        });

        viernes.setText("Viernes");
        viernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viernesActionPerformed(evt);
            }
        });

        primeraH.setText("15:00-15:55");
        primeraH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraHActionPerformed(evt);
            }
        });

        segundaH.setText("15:55-16:50");
        segundaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundaHActionPerformed(evt);
            }
        });

        terceraH.setText("16:50-17:45");
        terceraH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceraHActionPerformed(evt);
            }
        });

        cuartaH.setText("18:00-18:55");
        cuartaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartaHActionPerformed(evt);
            }
        });

        quintaH.setText("18:55-19:50");
        quintaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quintaHActionPerformed(evt);
            }
        });

        sextaH.setText("19:50-20:45");
        sextaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sextaHActionPerformed(evt);
            }
        });

        dia.setText("Debe seleccionar un día");

        hora.setText("Debe Seleccionar una hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(22, 809, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lunes)
                                    .addComponent(martes)
                                    .addComponent(miercoles)
                                    .addComponent(jueves)
                                    .addComponent(viernes))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quintaH)
                                    .addComponent(cuartaH)
                                    .addComponent(terceraH)
                                    .addComponent(sextaH)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(segundaH)
                                            .addComponent(primeraH))
                                        .addGap(24, 24, 24)
                                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 557, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lunes)
                            .addComponent(primeraH))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(martes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(miercoles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jueves)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viernes)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(segundaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(terceraH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuartaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quintaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sextaH))))
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String texto = textField1.getText();
        System.out.println(fila + " " + columna);
        // Limpiar todas las celdas de la tabla inicialmente
        if (columna == 0) {
            dia.setVisible(true);
        }
        if (fila == -1) {
            hora.setVisible(true);
        } else {
            limpiarTabla();
            jTable1.setValueAt(texto, fila, columna);
            dia.setVisible(false);
            hora.setVisible(false);

        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textField1ActionPerformed

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here
        popupMenu1.add("aï¿½adir");
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void lunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesActionPerformed
        // TODO add your handling code here:
        if (lunes.isSelected()) {
            columna = 1;
            martes.setSelected(false);
            miercoles.setSelected(false);
            jueves.setSelected(false);
            viernes.setSelected(false);
        } else {
            columna = -1;
        }

    }//GEN-LAST:event_lunesActionPerformed

    private void martesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martesActionPerformed
        // TODO add your handling code here:
        if (martes.isSelected()) {
            columna = 2;
            lunes.setSelected(false);
            miercoles.setSelected(false);
            jueves.setSelected(false);
            viernes.setSelected(false);
        }else {
            columna = -1;
        }

    }//GEN-LAST:event_martesActionPerformed

    private void miercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miercolesActionPerformed
        // TODO add your handling code here:
        if (miercoles.isSelected()) {
            columna = 3;
            martes.setSelected(false);
            lunes.setSelected(false);
            jueves.setSelected(false);
            viernes.setSelected(false);
        }else {
            columna = -1;
        }

    }//GEN-LAST:event_miercolesActionPerformed

    private void juevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juevesActionPerformed
        // TODO add your handling code here:
        if (jueves.isSelected()) {
            columna = 4;
            martes.setSelected(false);
            miercoles.setSelected(false);
            lunes.setSelected(false);
            viernes.setSelected(false);
        }else {
            columna = -1;
        }

    }//GEN-LAST:event_juevesActionPerformed

    private void viernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viernesActionPerformed
        // TODO add your handling code here:
        if (viernes.isSelected()) {
            columna = 5;
            martes.setSelected(false);
            miercoles.setSelected(false);
            jueves.setSelected(false);
            lunes.setSelected(false);
        }else {
            columna = -1;
        }

    }//GEN-LAST:event_viernesActionPerformed

    private void primeraHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraHActionPerformed
        // TODO add your handling code here:
        if (primeraH.isSelected()) {
            fila = 0;
            segundaH.setSelected(false);
            terceraH.setSelected(false);
            cuartaH.setSelected(false);
            quintaH.setSelected(false);
            sextaH.setSelected(false);
        } else
            fila = -1;
    }//GEN-LAST:event_primeraHActionPerformed

    private void segundaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundaHActionPerformed
        // TODO add your handling code here:
        if (segundaH.isSelected()) {
            fila = 1;
            primeraH.setSelected(false);
            terceraH.setSelected(false);
            cuartaH.setSelected(false);
            quintaH.setSelected(false);
            sextaH.setSelected(false);
        } else
            fila = -1;
    }//GEN-LAST:event_segundaHActionPerformed

    private void terceraHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceraHActionPerformed
        // TODO add your handling code here:
        if (terceraH.isSelected()) {
            fila = 2;
            segundaH.setSelected(false);
            primeraH.setSelected(false);
            cuartaH.setSelected(false);
            quintaH.setSelected(false);
            sextaH.setSelected(false);
        }else
            fila = -1;
    }//GEN-LAST:event_terceraHActionPerformed

    private void cuartaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartaHActionPerformed
        // TODO add your handling code here:
        if (cuartaH.isSelected()) {
            fila = 4;
            segundaH.setSelected(false);
            terceraH.setSelected(false);
            primeraH.setSelected(false);
            quintaH.setSelected(false);
            sextaH.setSelected(false);
        }else
            fila = -1;
    }//GEN-LAST:event_cuartaHActionPerformed

    private void quintaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quintaHActionPerformed
        // TODO add your handling code here:
        if (quintaH.isSelected()) {
            fila = 5;
            segundaH.setSelected(false);
            terceraH.setSelected(false);
            cuartaH.setSelected(false);
            primeraH.setSelected(false);
            sextaH.setSelected(false);
        }else
            fila = -1;
    }//GEN-LAST:event_quintaHActionPerformed

    private void sextaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sextaHActionPerformed
        // TODO add your handling code here:
        if (sextaH.isSelected()) {
            fila = 6;
            segundaH.setSelected(false);
            terceraH.setSelected(false);
            cuartaH.setSelected(false);
            quintaH.setSelected(false);
            primeraH.setSelected(false);
        }else
            fila = -1;
    }//GEN-LAST:event_sextaHActionPerformed

    /**
     * @param args the command line arguments
     */
    private int columna;
    private int fila;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cuartaH;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jueves;
    private javax.swing.JCheckBox lunes;
    private javax.swing.JCheckBox martes;
    private java.awt.MenuItem menuItem1;
    private javax.swing.JCheckBox miercoles;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JCheckBox primeraH;
    private javax.swing.JCheckBox quintaH;
    private javax.swing.JCheckBox segundaH;
    private javax.swing.JCheckBox sextaH;
    private javax.swing.JCheckBox terceraH;
    private java.awt.TextField textField1;
    private javax.swing.JCheckBox viernes;
    // End of variables declaration//GEN-END:variables
}
